### ISSUE TITLE
Ever heard of IPFS?

### ISSUE THREAD

**Issue by olso** [elendirx/web2web#1]
https://ipfs.io

https://gateway.ipfs.io/ipfs/QmTeW79w7QQ6Npa3b1d5tANreCDxF2iDaAPsDvW6KtLmfB/docs/examples/

**Comment by elendirx** [comment]
Looks like an interesting and quite mature project. Am I reinventing the wheel here?

**Comment by qgustavor** [comment]
I don't know a lot about IPFS, but one of the problems I see with with IPFS (and similar ideas) for now is requiring to download and install some software. In future, if it gets popular there is no problem, but for now it's a barrier for many users. Of course there is the gateway, but it only acts as a... gateway, isn't the equivalent for the software.

A good thing about this idea is because it allows running directly in a browser. Even if a browser isn't the best platform for this idea it being possible to easily use it - not just a "watch demo" - is good to make it more popular. IHMO is important making some idea popular: if [there are many similar projects](https://news.ycombinator.com/item?id=12502611) will people download clients for all of those? I think they don't.

In the other hand when it runs directly on the browser Web2Web also don't solves problems like "losing control over a web server or a domain" even if it implements Service Workers to keep working when the control of the server or the domain is lost. The Service Workers are made to always being updated, preventing that bugs persist for a long time, so they can be removed by the new server/domain owner. 

But you can detect when the Service Worker changes and alert users that something is wrong and allow downloading a copy of the cached "index.html" or suggesting to download the client software. But [it's quite complicated](https://github.com/qgustavor/signed-service-workers) and maybe meaningless.

Other problem: web2web depends on blockexplorer.com: if it gets down the everything gets down. Maybe it could use many services, but there's still a chance of all of those get down. Also, more services you use higher is the chance of one of those lying and making people download a fake torrent, so you also need verify bitcoin data. Some people [on HackerNews](https://news.ycombinator.com/item?id=12502559) cited BEP 46 (updateable torrents), that could be implemented by WebTorrent (if they also [implement WebRTC DHT](https://github.com/feross/webtorrent/issues/288)), but was some issues (Sybil attacks). Also quite complicated and maybe meaningless...

I think that it's a good idea, but because [xkcd](https://xkcd.com/927/) improving one of the existing projects could be a better idea.

**Comment by elendirx** [comment]
@qgustavor Good points. And thanks for the links, I'm always happy to learn something new.

**Comment by gigix** [comment]
@qgustavor Which existing project would you recommend? We have a small team here getting excited by @elendirx 's idea and willing to contribute. But as you correctly pointed out, it is better to focus the community effort.

**Comment by millette** [comment]
[ephemeral2](https://github.com/losvedir/ephemeral2) is another similar project, hasn't been updated in over a year though. And there's the mothership the [redecentralize/alternative-internet](https://github.com/redecentralize/alternative-internet) project.

**Comment by JackBekket** [comment]
@qgustavor  

It is not necessery work from gatewy, you can do it throw browser like webtorrent, just use https://github.com/ipfs/js-ipfs

**Comment by JackBekket** [comment]
I think I will do implementation of this project on Ethereum Blockchain + IPFS

**Comment by michaelimfeld** [comment]
https://github.com/HelloZeroNet/ZeroNet seems to be a similar project too ...

**Comment by JackBekket** [comment]
Guys, u know, as I see here - there are a lot projects of Decentralized web from  BitTorrent shares to IPFS and many different implementation of it, and every project build on idea of sharing files of site with each other. But how about some page processor, like PHP or Node.js, something,that could replace the server itself? Do u know something like that for exept Ethereum Dapps? (Eth. Dapps are really working but they focuced on business and finance logic and sometimes to expensive)
